spring.application.name=mediconnect

# Context Path
server.servlet.context-path=/mediconnect

spring.datasource.url=jdbc:mysql://localhost:3306/mediconnect
spring.datasource.username=root
spring.datasource.password=mahendra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cross.origin.value=http://10.26.3.76:3000
cross.origin.localhost.value=http://localhost:3000

gemini.api.key=AIzaSyBWR9qoq0L4B2mPr__DaGvtf2m0MYgEBMY

